import { ClientProfile, MasterData, Clause, AuditLog, SystemNotification } from '../types';

export const TN_MASTER_DATA: MasterData = {
  documentTypes: [
    { id: 'dt1', code: 'SALE', nameEn: 'Sale Deed', nameTa: 'க்கிரயப் பத்திரம்' },
    { id: 'dt2', code: 'GIFT', nameEn: 'Gift Settlement Deed', nameTa: 'தான செட்டில்மெண்ட் பத்திரம்' },
    { id: 'dt3', code: 'SETTLE', nameEn: 'Family Settlement Deed', nameTa: 'குடும்ப செட்டில்மெண்ட் பத்திரம்' },
    { id: 'dt4', code: 'PARTITION', nameEn: 'Partition Deed', nameTa: 'பாகப்பிரிவினை பத்திரம்' },
    { id: 'dt5', code: 'LEASE', nameEn: 'Lease Deed', nameTa: 'வாடகை / குத்தகை பத்திரம்' },
    { id: 'dt6', code: 'MORTGAGE', nameEn: 'Mortgage Deed', nameTa: 'அடமானப் பத்திரம்' },
  ],
  documentSubtypes: [
    { id: 'dst1', code: 'SALE_METRO', nameEn: 'Sale in Metro Area', nameTa: 'மாநகராட்சி எல்லைக்குள் கிரயம்' },
    { id: 'dst2', code: 'SALE_PANCHAYAT', nameEn: 'Sale in Panchayat Area', nameTa: 'ஊராட்சி எல்லைக்குள் கிரயம்' },
    { id: 'dst3', code: 'GIFT_FAMILY', nameEn: 'Gift to Family Member', nameTa: 'குடும்ப உறுப்பினருக்கு கொடை' },
    { id: 'dst4', code: 'LEASE_RES', nameEn: 'Residential Lease', nameTa: 'குடியிருப்பு வாடகை' },
  ],
  partyRoles: [
    { id: 'pr1', code: 'SELLER', nameEn: 'Vendor / Seller', nameTa: 'கிரயதாரர் / விற்பனையாளர்' },
    { id: 'pr2', code: 'BUYER', nameEn: 'Vendee / Purchaser', nameTa: 'வாங்குபவர்' },
    { id: 'pr3', code: 'DONOR', nameEn: 'Donor / Settlor', nameTa: 'கொடையாளர்' },
    { id: 'pr4', code: 'DONEE', nameEn: 'Donee / Settlee', nameTa: 'கொடையைப் பெறுபவர்' },
    { id: 'pr5', code: 'WITNESS', nameEn: 'Witness', nameTa: 'சாட்சி' },
  ],
  occupationMaster: [
    { id: 'oc1', code: 'AGRI', nameEn: 'Agriculture', nameTa: 'விவசாயம்' },
    { id: 'oc2', code: 'BUSINESS', nameEn: 'Business', nameTa: 'தொழில் / வியாபாரம்' },
    { id: 'oc3', code: 'PVT', nameEn: 'Private Service', nameTa: 'தனியார் வேலை' },
    { id: 'oc4', code: 'GOVT', nameEn: 'Government Service', nameTa: 'அரசு வேலை' },
    { id: 'oc5', code: 'PROF', nameEn: 'Professional (Doctor/Lawyer/Eng)', nameTa: 'தொழில்முறை வல்லுநர்' },
    { id: 'oc6', code: 'HOMEMAKER', nameEn: 'Homemaker', nameTa: 'இல்லத்தரசி' },
    { id: 'oc7', code: 'RETIRED', nameEn: 'Retired', nameTa: 'ஓய்வு பெற்றவர்' },
  ],
  relationshipMaster: [
    { id: 'rm1', code: 'S_O', nameEn: 'Son of', nameTa: 'மகன்' },
    { id: 'rm2', code: 'D_O', nameEn: 'Daughter of', nameTa: 'மகள்' },
    { id: 'rm3', code: 'W_O', nameEn: 'Wife of', nameTa: 'மனைவி' },
    { id: 'rm4', code: 'H_O', nameEn: 'Husband of', nameTa: 'கணவர்' },
    { id: 'rm5', code: 'C_O', nameEn: 'Care of', nameTa: 'பாதுகாவலர்' },
  ],
  districtMaster: [
    { id: 'd1', code: 'ARI', nameEn: 'Ariyalur', nameTa: 'அரியலூர்' },
    { id: 'd2', code: 'CGL', nameEn: 'Chengalpattu', nameTa: 'செங்கல்பட்டு' },
    { id: 'd3', code: 'CHN', nameEn: 'Chennai', nameTa: 'சென்னை' },
    { id: 'd4', code: 'CBE', nameEn: 'Coimbatore', nameTa: 'கோயம்புத்தூர்' },
    { id: 'd5', code: 'CUD', nameEn: 'Cuddalore', nameTa: 'கடலூர்' },
    { id: 'd6', code: 'DK', nameEn: 'Dharmapuri', nameTa: 'தர்மபுரி' },
    { id: 'd7', code: 'DG', nameEn: 'Dindigul', nameTa: 'திண்டுக்கல்' },
    { id: 'd8', code: 'ERD', nameEn: 'Erode', nameTa: 'ஈரோடு' },
    { id: 'd9', code: 'KLK', nameEn: 'Kallakurichi', nameTa: 'கள்ளக்குறிச்சி' },
    { id: 'd10', code: 'KCP', nameEn: 'Kanchipuram', nameTa: 'காஞ்சிபுரம்' },
    { id: 'd11', code: 'KK', nameEn: 'Kanyakumari', nameTa: 'கன்னியாகுமரி' },
    { id: 'd12', code: 'KRR', nameEn: 'Karur', nameTa: 'கரூர்' },
    { id: 'd13', code: 'KRG', nameEn: 'Krishnagiri', nameTa: 'கிருஷ்ணகிரி' },
    { id: 'd14', code: 'MDU', nameEn: 'Madurai', nameTa: 'மதுரை' },
    { id: 'd15', code: 'MYD', nameEn: 'Mayiladuthurai', nameTa: 'மயிலாடுதுறை' },
    { id: 'd16', code: 'NGP', nameEn: 'Nagapattinam', nameTa: 'நாகப்பட்டினம்' },
    { id: 'd17', code: 'NMK', nameEn: 'Namakkal', nameTa: 'நாமக்கல்' },
    { id: 'd18', code: 'NLG', nameEn: 'Nilgiris', nameTa: 'நீலகிரி' },
    { id: 'd19', code: 'PBL', nameEn: 'Perambalur', nameTa: 'பெரம்பலூர்' },
    { id: 'd20', code: 'PDK', nameEn: 'Pudukkottai', nameTa: 'புதுக்கோட்டை' },
    { id: 'd21', code: 'RMD', nameEn: 'Ramanathapuram', nameTa: 'இராமநாதபுரம்' },
    { id: 'd22', code: 'RPT', nameEn: 'Ranipet', nameTa: 'இராணிப்பேட்டை' },
    { id: 'd23', code: 'SLM', nameEn: 'Salem', nameTa: 'சேலம்' },
    { id: 'd24', code: 'SVG', nameEn: 'Sivaganga', nameTa: 'சிவகங்கை' },
    { id: 'd25', code: 'TKS', nameEn: 'Tenkasi', nameTa: 'தென்காசி' },
    { id: 'd26', code: 'TJV', nameEn: 'Thanjavur', nameTa: 'தஞ்சாவூர்' },
    { id: 'd27', code: 'TNI', nameEn: 'Theni', nameTa: 'தேனி' },
    { id: 'd28', code: 'TUT', nameEn: 'Thoothukudi', nameTa: 'தூத்துக்குடி' },
    { id: 'd29', code: 'TRY', nameEn: 'Tiruchirappalli', nameTa: 'திருச்சிராப்பள்ளி' },
    { id: 'd30', code: 'TNV', nameEn: 'Tirunelveli', nameTa: 'திருநெல்வேலி' },
    { id: 'd31', code: 'TPR', nameEn: 'Tirupattur', nameTa: 'திருப்பத்தூர்' },
    { id: 'd32', code: 'TPP', nameEn: 'Tiruppur', nameTa: 'திருப்பூர்' },
    { id: 'd33', code: 'TVR', nameEn: 'Tiruvallur', nameTa: 'திருவள்ளூர்' },
    { id: 'd34', code: 'TVM', nameEn: 'Tiruvannamalai', nameTa: 'திருவண்ணாமலை' },
    { id: 'd35', code: 'TVU', nameEn: 'Tiruvarur', nameTa: 'திருவாரூர்' },
    { id: 'd36', code: 'VEL', nameEn: 'Vellore', nameTa: 'வேலூர்' },
    { id: 'd37', code: 'VLP', nameEn: 'Viluppuram', nameTa: 'விழுப்புரம்' },
    { id: 'd38', code: 'VRD', nameEn: 'Virudhunagar', nameTa: 'விருதுநகர்' }
  ],
  registrationDistrictMaster: [
    { id: 'rd1', code: 'RD_CH_S', nameEn: 'Chennai South', nameTa: 'தென் சென்னை' },
    { id: 'rd2', code: 'RD_CH_N', nameEn: 'Chennai North', nameTa: 'வட சென்னை' },
    { id: 'rd3', code: 'RD_CH_C', nameEn: 'Chennai Central', nameTa: 'மத்திய சென்னை' },
    { id: 'rd4', code: 'RD_CGL', nameEn: 'Chengalpattu', nameTa: 'செங்கல்பட்டு' },
    { id: 'rd5', code: 'RD_VEL', nameEn: 'Vellore', nameTa: 'வேலூர்' },
    { id: 'rd6', code: 'RD_TPR', nameEn: 'Tirupattur', nameTa: 'திருப்பத்தூர்' },
    { id: 'rd7', code: 'RD_SLM', nameEn: 'Salem', nameTa: 'சேலம்' },
    { id: 'rd8', code: 'RD_MDU', nameEn: 'Madurai', nameTa: 'மதுரை' },
    { id: 'rd9', code: 'RD_TNV', nameEn: 'Tirunelveli', nameTa: 'திருநெல்வேலி' },
    { id: 'rd10', code: 'RD_TKS', nameEn: 'Tenkasi', nameTa: 'தென்காசி' },
    { id: 'rd11', code: 'RD_KLK', nameEn: 'Kallakurichi', nameTa: 'கள்ளக்குறிச்சி' },
    { id: 'rd12', code: 'RD_MYD', nameEn: 'Mayiladuthurai', nameTa: 'மயிலாடுதுறை' },
    { id: 'rd13', code: 'RD_KRG', nameEn: 'Krishnagiri', nameTa: 'கிருஷ்ணகிரி' },
  ],
  talukMaster: [
    { id: 't1', code: 'MYL', nameEn: 'Mylapore', nameTa: 'மயிலாப்பூர்', extra: { districtId: 'd3' } },
    { id: 't2', code: 'SHO', nameEn: 'Sholinganallur', nameTa: 'சோழிங்கநல்லூர்', extra: { districtId: 'd3' } },
    { id: 't3', code: 'VEL_T', nameEn: 'Velachery', nameTa: 'வேளச்சேரி', extra: { districtId: 'd3' } },
    { id: 't4', code: 'CGL_T', nameEn: 'Chengalpattu', nameTa: 'செங்கல்பட்டு', extra: { districtId: 'd2' } },
    { id: 't5', code: 'TAM_T', nameEn: 'Tambaram', nameTa: 'தாம்பரம்', extra: { districtId: 'd2' } },
    { id: 't6', code: 'KAN_T', nameEn: 'Kanchipuram', nameTa: 'காஞ்சிபுரம்', extra: { districtId: 'd10' } },
    { id: 't7', code: 'SRI_T', nameEn: 'Sriperumbudur', nameTa: 'ஸ்ரீபெரும்புதூர்', extra: { districtId: 'd10' } },
    { id: 't8', code: 'KAT_T', nameEn: 'Katpadi', nameTa: 'காட்பாடி', extra: { districtId: 'd36' } },
    { id: 't9', code: 'VEL_T_REV', nameEn: 'Vellore', nameTa: 'வேலூர்', extra: { districtId: 'd36' } },
    { id: 't10', code: 'TPR_T', nameEn: 'Tirupattur', nameTa: 'திருப்பத்தூர்', extra: { districtId: 'd31' } },
    { id: 't11', code: 'VAN_T', nameEn: 'Vaniyambadi', nameTa: 'வாணியம்பாடி', extra: { districtId: 'd31' } },
    { id: 't12', code: 'WAL_T', nameEn: 'Walajapet', nameTa: 'வாலாஜாபேட்டை', extra: { districtId: 'd22' } },
    { id: 't13', code: 'KLK_T', nameEn: 'Kallakurichi', nameTa: 'கள்ளக்குறிச்சி', extra: { districtId: 'd9' } },
    { id: 't14', code: 'SAN_T', nameEn: 'Sankarapuram', nameTa: 'சங்கராபுரம்', extra: { districtId: 'd9' } },
    { id: 't15', code: 'VLP_T', nameEn: 'Viluppuram', nameTa: 'விழுப்புரம்', extra: { districtId: 'd37' } },
    { id: 't16', code: 'TKS_T', nameEn: 'Tenkasi', nameTa: 'தென்காசி', extra: { districtId: 'd25' } },
    { id: 't17', code: 'TNV_T', nameEn: 'Tirunelveli', nameTa: 'திருநெல்வேலி', extra: { districtId: 'd30' } },
    { id: 't18', code: 'MYD_T', nameEn: 'Mayiladuthurai', nameTa: 'மயிலாடுதுறை', extra: { districtId: 'd15' } },
    { id: 't19', code: 'NGP_T', nameEn: 'Nagapattinam', nameTa: 'நாகப்பட்டினம்', extra: { districtId: 'd16' } },
    { id: 't20', code: 'KRG_T', nameEn: 'Krishnagiri', nameTa: 'கிருஷ்ணகிரி', extra: { districtId: 'd13' } },
  ],
  villageMaster: [
    { id: 'v1', code: 'TVM', nameEn: 'Thiruvanmiyur', nameTa: 'திருவான்மியூர்', extra: { talukId: 't2' } },
    { id: 'v2', code: 'VEL_V', nameEn: 'Velachery Village', nameTa: 'வேளச்சேரி கிராமம்', extra: { talukId: 't3' } },
    { id: 'v3', code: 'MYL_V', nameEn: 'Mylapore Village', nameTa: 'மயிலாப்பூர் கிராமம்', extra: { talukId: 't1' } },
    { id: 'v4', code: 'CHIT_V', nameEn: 'Chitlapakkam', nameTa: 'சிட்லபாக்கம்', extra: { talukId: 't5' } },
    { id: 'v5', code: 'TAM_V', nameEn: 'Tambaram Village', nameTa: 'தாம்பரம் கிராமம்', extra: { talukId: 't5' } },
    { id: 'v6', code: 'CGL_V', nameEn: 'Chengalpattu Town', nameTa: 'செங்கல்பட்டு நகரம்', extra: { talukId: 't4' } },
    { id: 'v7', code: 'KAN_V', nameEn: 'Kanchipuram Village', nameTa: 'காஞ்சிபுரம் கிராமம்', extra: { talukId: 't6' } },
    { id: 'v8', code: 'KAT_V', nameEn: 'Katpadi Village', nameTa: 'காட்பாடி கிராமம்', extra: { talukId: 't8' } },
    { id: 'v9', code: 'SAT_V', nameEn: 'Sathuvachari', nameTa: 'சத்துவாச்சாரி', extra: { talukId: 't9' } },
    { id: 'v10', code: 'TPR_V', nameEn: 'Tirupattur Town', nameTa: 'திருப்பத்தூர் நகரம்', extra: { talukId: 't10' } },
    { id: 'v11', code: 'VAN_V', nameEn: 'Vaniyambadi Village', nameTa: 'வாணியம்பாடி கிராமம்', extra: { talukId: 't11' } },
    { id: 'v12', code: 'RAN_V', nameEn: 'Ranipet Town', nameTa: 'இராணிப்பேட்டை நகரம்', extra: { talukId: 't12' } },
    { id: 'v13', code: 'KLK_V', nameEn: 'Kallakurichi Village', nameTa: 'கள்ளக்குறிச்சி கிராமம்', extra: { talukId: 't13' } },
    { id: 'v14', code: 'VLP_V', nameEn: 'Viluppuram Town', nameTa: 'விழுப்புரம் நகரம்', extra: { talukId: 't15' } },
    { id: 'v15', code: 'TKS_V', nameEn: 'Tenkasi Village', nameTa: 'தென்காசி கிராமம்', extra: { talukId: 't16' } },
    { id: 'v16', code: 'TNV_V', nameEn: 'Tirunelveli Town', nameTa: 'திருநெல்வேலி நகரம்', extra: { talukId: 't17' } },
    { id: 'v17', code: 'MYD_V', nameEn: 'Mayiladuthurai Town', nameTa: 'மயிலாடுதுறை நகரம்', extra: { talukId: 't18' } },
    { id: 'v18', code: 'NGP_V', nameEn: 'Nagapattinam Village', nameTa: 'நாகப்பட்டினம் கிராமம்', extra: { talukId: 't19' } },
    { id: 'v19', code: 'KRG_V', nameEn: 'Krishnagiri Village', nameTa: 'கிருஷ்ணகிரி கிராமம்', extra: { talukId: 't20' } },
  ],
  sroMaster: [
    { id: 'sro1', code: 'SRO_MYL_1', nameEn: 'SRO Mylapore (Joint-I)', nameTa: 'மயிலாப்பூர் Joint-I சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd1' } },
    { id: 'sro2', code: 'SRO_MYL_2', nameEn: 'SRO Mylapore (Joint-II)', nameTa: 'மயிலாப்பூர் Joint-II சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd1' } },
    { id: 'sro3', code: 'SRO_TVM', nameEn: 'SRO Thiruvanmiyur', nameTa: 'திருவான்மியூர் சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd1' } },
    { id: 'sro4', code: 'SRO_VEL_S', nameEn: 'SRO Velachery', nameTa: 'வேளச்சேரி சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd1' } },
    { id: 'sro5', code: 'SRO_CGL', nameEn: 'SRO Chengalpattu', nameTa: 'செங்கல்பட்டு சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd4' } },
    { id: 'sro6', code: 'SRO_TAM', nameEn: 'SRO Tambaram', nameTa: 'தாம்பரம் சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd4' } },
    { id: 'sro7', code: 'SRO_VEL', nameEn: 'SRO Vellore', nameTa: 'வேலூர் சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd5' } },
    { id: 'sro8', code: 'SRO_KAT', nameEn: 'SRO Katpadi', nameTa: 'காட்பாடி சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd5' } },
    { id: 'sro9', code: 'SRO_TPR', nameEn: 'SRO Tirupattur', nameTa: 'திருப்பத்தூர் சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd6' } },
    { id: 'sro10', code: 'SRO_VAN', nameEn: 'SRO Vaniyambadi', nameTa: 'வாணியம்பாடி சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd6' } },
    { id: 'sro11', code: 'SRO_TKS', nameEn: 'SRO Tenkasi', nameTa: 'தென்காசி சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd10' } },
    { id: 'sro12', code: 'SRO_KAD', nameEn: 'SRO Kadayanallur', nameTa: 'கடையநல்லூர் சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd10' } },
    { id: 'sro13', code: 'SRO_KLK', nameEn: 'SRO Kallakurichi', nameTa: 'கள்ளக்குறிச்சி சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd11' } },
    { id: 'sro14', code: 'SRO_MYD', nameEn: 'SRO Mayiladuthurai', nameTa: 'மயிலாடுதுறை சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd12' } },
    { id: 'sro15', code: 'SRO_SIR', nameEn: 'SRO Sirkazhi', nameTa: 'சீர்காழி சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd12' } },
    { id: 'sro16', code: 'SRO_KRG', nameEn: 'SRO Krishnagiri', nameTa: 'கிருஷ்ணகிரி சார்பதிவாளர் அலுவலகம்', extra: { registrationDistrictId: 'rd13' } },
  ],
  propertyTypeMaster: [
    { id: 'pt1', code: 'RES_LAND', nameEn: 'Residential Plot / Land', nameTa: 'மனை / குடியிருப்பு நிலம்' },
    { id: 'pt2', code: 'FLAT', nameEn: 'Flat / Apartment', nameTa: 'பிளாட் / அடுக்குமாடி குடியிருப்பு' },
    { id: 'pt3', code: 'AGRI_LAND', nameEn: 'Agricultural Wet Land (Nanjai)', nameTa: 'நஞ்சை விவசாய நிலம்' },
    { id: 'pt4', code: 'AGRI_DRY', nameEn: 'Agricultural Dry Land (Punjai)', nameTa: 'புஞ்சை விவசாய நிலம்' },
    { id: 'pt5', code: 'COMM', nameEn: 'Commercial Building', nameTa: 'வணிகக் கட்டிடம்' },
  ],
};

export const DUMMY_CLIENTS: ClientProfile[] = [
  {
    id: 'c1',
    name: 'M. Selvakumar',
    fatherName: 'Muthuswamy Mudaliar',
    dob: '1975-04-12',
    age: 51,
    occupation: 'Private Service',
    pan: 'ABCPS1234F',
    aadhaar: '4589-1234-5678',
    address: 'No. 45, First Main Road, Thiruvanmiyur, Chennai - 600041',
    phone: '9840123456',
    email: 'selvakumar.m@example.com',
    createdAt: '2026-01-10T14:22:00Z',
  },
  {
    id: 'c2',
    name: 'R. Rajeshwari',
    fatherName: 'Ramachandran Iyer',
    dob: '1982-11-23',
    age: 43,
    occupation: 'Business',
    pan: 'ABZPR9876Q',
    aadhaar: '8954-4321-8765',
    address: 'Old No. 12, New No. 28, Venkatesa Agragaram, Mylapore, Chennai - 600004',
    phone: '9444012345',
    email: 'rajeshwari.r@example.com',
    createdAt: '2026-02-15T09:11:00Z',
  },
  {
    id: 'c3',
    name: 'K. Kathiravan',
    fatherName: 'Karuppiah Pillai',
    dob: '1990-08-05',
    age: 35,
    occupation: 'Agriculture',
    pan: 'CLKPK5566T',
    aadhaar: '2345-6789-0123',
    address: 'Pillayar Kovil Street, Chitlapakkam, Tambaram, Chennai - 600064',
    phone: '9884112233',
    email: 'kathir.k@example.com',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'c4',
    name: 'S. Aruna Vadivel',
    fatherName: 'Subramanian Achari',
    dob: '1968-01-30',
    age: 58,
    occupation: 'Homemaker',
    pan: 'DEFPA9900H',
    aadhaar: '9012-3456-7890',
    address: 'Flat A3, Shanti Apartments, Velachery, Chennai - 600042',
    phone: '9790123456',
    email: 'arunavadivel@example.com',
    createdAt: '2026-03-18T16:45:00Z',
  },
];

export const STANDARD_CLAUSES: Clause[] = [
  // --- MANDATORY COVENANTS ---
  {
    id: 'marketable_title',
    title: 'Marketable Title Assurance',
    category: 'Mandatory',
    contentEn: 'The Vendor hereby covenants with the Purchaser that the Vendor has absolute right, full power and absolute authority to sell, transfer and convey the Scheduled Property hereby sold and that the Vendor has not done any act or suffered anything whereby their right to sell and convey has been impaired.',
    contentTa: 'விற்பனையாளர் இதன் மூலம் வாங்குபவருக்கு உறுதி அளிப்பது என்னவென்றால், விற்கப்படும் சொத்தை விற்பதற்கும், மாற்றுவதற்கும், ஒப்படைப்பதற்கும் தங்களுக்கு முழுமையான மற்றும் தடையற்ற உரிமை உள்ளது. மேலும் தங்களின் சொத்து மாற்று உரிமையை பாதிக்கும் எந்தவொரு செயலையும் தாங்கள் செய்யவில்லை என்று உறுதியளிக்கிறார்.',
    isActive: true,
    isMandatory: true,
  },
  {
    id: 'encumbrance_clear',
    title: 'Encumbrance Clear Covenant',
    category: 'Mandatory',
    contentEn: 'The Vendor declares and assures the Purchaser that the Scheduled Property is free from all encumbrances, charges, liens, attachments, legal disputes, mortgages or acquisitions by government authorities, and should any charge be found, the Vendor covenants to clear the same at their own cost and indemnify the Purchaser against all losses.',
    contentTa: 'அட்டவணைப்படுத்தப்பட்ட சொத்தின் மீது எவ்விதமான வில்லங்கங்கள், கடன்கள், ஜப்திகள், நீதிமன்ற வழக்குகள், அடமானங்கள் அல்லது அரசாங்க கையகப்படுத்துதல்கள் ஏதுமில்லை என்று விற்பனையாளர் உறுதியளிக்கிறார். சொத்தில் ஏதேனும் வில்லங்கம் இருப்பதாகப் பிற்காலத்தில் தெரியவந்தால், அதை விற்பனையாளர் சொந்த செலவில் தீர்த்து, வாங்குபவருக்கு ஏற்படும் இழப்புகளுக்கு ஈடுசெய்வார்.',
    isActive: true,
    isMandatory: true,
  },
  {
    id: 'possession_delivery',
    title: 'Peaceful Possession Delivery',
    category: 'Mandatory',
    contentEn: 'The Vendor has on this day delivered vacant, peaceful and physical possession of the Scheduled Property to the Purchaser, and the Purchaser shall henceforth hold, possess and enjoy the same as absolute owner without any hindrance or interruption from the Vendor or any persons claiming under them.',
    contentTa: 'சொத்தின் மீதான வெற்று, அமைதியான மற்றும் நேரடி சுவாதீனத்தை விற்பனையாளர் இன்று வாங்குபவரிடம் ஒப்படைத்துவிட்டார். இதன் மூலம் வாங்குபவர் இச்சொத்தை எவ்வித இடையூறும் இன்றி முழு உரிமையுடன் அனுபவிக்கலாம்.',
    isActive: true,
    isMandatory: true,
  },
  {
    id: 'consideration_declaration',
    title: 'Consideration Declaration',
    category: 'Mandatory',
    contentEn: 'The Vendor hereby acknowledges the receipt of the full and final consideration amount as agreed between both parties, and declares that no further payments are outstanding from the Purchaser in respect of this absolute transfer.',
    contentTa: 'இரு தரப்பினராலும் ஒப்புக்கொள்ளப்பட்ட முழுமையான மற்றும் இறுதியான கிரயத் தொகையைப் பெற்றுக் கொண்டதை விற்பனையாளர் இதன் மூலம் ஒப்புக்கொள்கிறார், மேலும் இந்த முழுமையான உரிமை மாற்றத்திற்கு வாங்குபவரிடமிருந்து மேற்கொண்டு எந்தவொரு நிலுவைத் தொகையும் இல்லை என்றும் அறிவிக்கிறார்.',
    isActive: true,
    isMandatory: true,
  },
  {
    id: 'ownership_warranty',
    title: 'Ownership Warranty',
    category: 'Mandatory',
    contentEn: 'The Vendor warrants that they are the sole, lawful, and absolute owner of the Scheduled Property, possessing clear, marketable title, and have not executed any prior agreement, deed of sale, mortgage, or transfer in favor of any other person.',
    contentTa: 'விற்பனையாளர் தாங்கள் மட்டுமே சொத்தின் சட்டப்பூர்வமான மற்றும் முழுமையான உரிமையாளர் என்றும், தெளிவான மற்றும் விற்கத்தக்க உரிமையைக் கொண்டுள்ளனர் என்றும், வேறு எந்த நபருக்கும் முந்தைய உடன்படிக்கை, கிரயப் பத்திரம், அடமானம் அல்லது உரிமை மாற்றம் எதையும் செய்யவில்லை என்றும் உத்தரவாதம் அளிக்கிறார்.',
    isActive: true,
    isMandatory: true,
  },

  // --- RECOMMENDED COVENANTS ---
  {
    id: 'tax_outgoings',
    title: 'Tax and Outgoings Settlement',
    category: 'Recommended',
    contentEn: 'All taxes, rates, assessments, electricity charges, and other outgoings payable in respect of the Scheduled Property up to the date of execution of this deed have been fully paid and discharged by the Vendor, and thereafter the same shall be paid by the Purchaser.',
    contentTa: 'இன்றுவரை சொத்து வரி, மின்சார கட்டணம், இதர வரிகள் மற்றும் அரசு நிலுவைகள் அனைத்தையும் விற்பனையாளர் செலுத்திவிட்டார். இதற்குப் பிந்தைய வரிகள் மற்றும் அரசு கட்டணங்களை வாங்குபவரே செலுத்த வேண்டும்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'stamp_duty_liability',
    title: 'Stamp Duty and Registration Liability',
    category: 'Recommended',
    contentEn: 'It is agreed between the parties that the expenses towards stamp duty, registration fees, drafting charges, and computer fees for registration of this Sale Deed shall be solely borne and paid by the Purchaser.',
    contentTa: 'இக்கிரயப் பத்திரப் பதிவிற்கான முத்திரைத் தாள் கட்டணம், பதிவு கட்டணம், ஆவண எழுத்துக் கட்டணங்கள் ஆகிய அனைத்தையும் வாங்குபவரே முழுமையாக ஏற்க ஒப்புக்கொள்கிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'original_documents',
    title: 'Original Title Document Handover',
    category: 'Recommended',
    contentEn: 'The Vendor has on this day handed over all original title deeds, parent documents, tax receipts, and other relevant records relating to the Scheduled Property to the Purchaser, who acknowledges receipt of the same.',
    contentTa: 'சொத்தின் மூல ஆவணங்கள், தாய் பத்திரங்கள், வரி ரசீதுகள் மற்றும் சொத்து தொடர்பான அனைத்து அசல் ஆவணங்களையும் விற்பனையாளர் இன்று வாங்குபவரிடம் ஒப்படைத்துவிட்டார், வாங்குபவர் அதனைப் பெற்றுக் கொண்டதை ஒப்புக்கொள்கிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'patta_assistance',
    title: 'Patta / Mutation Transfer Assistance',
    category: 'Recommended',
    contentEn: 'The Vendor hereby covenants to cooperate, sign, and execute all necessary applications, declarations, and consent forms to assist the Purchaser in transferring the Patta, Chitta, Adangal, and municipal revenue records to the Purchaser\'s name.',
    contentTa: 'சொத்தின் பட்டா, சிட்டா, அடங்கல் மற்றும் நகராட்சி வருவாய்ப் பதிவேடுகளை வாங்குபவரின் பெயருக்கு மாற்றுவதற்குத் தேவையான அனைத்து விண்ணப்பங்கள், பிரகடனங்கள் மற்றும் சம்மதப் படிவங்களில் கையெழுத்திட்டு ஒத்துழைக்க விற்பனையாளர் ஒப்புக்கொள்கிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'no_prior_agreement',
    title: 'No Prior Agreement Declaration',
    category: 'Recommended',
    contentEn: 'The Vendor solemnly declares that they have not entered into any agreement for sale, lease, joint venture, or any other transaction with any third party concerning the Scheduled Property, and that no prior agreements of any kind are currently subsisting.',
    contentTa: 'அட்டவணைப்படுத்தப்பட்ட சொத்து தொடர்பாக வேறு எந்த மூன்றாம் தரப்பினருடனும் விற்பனை உடன்படிக்கை, குத்தகை, கூட்டு முயற்சி அல்லது வேறு எந்த பரிவர்த்தனையும் செய்யவில்லை என்றும், தற்போது எந்தவொரு முந்தைய உடன்படிக்கையும் நடைமுறையில் இல்லை என்றும் விற்பனையாளர் உறுதியளிக்கிறார்.',
    isActive: true,
    isMandatory: false,
  },

  // --- CONDITIONAL COVENANTS ---
  {
    id: 'mortgage_release',
    title: 'Mortgage Release & NOC Covenant',
    category: 'Conditional',
    contentEn: 'In the event of any outstanding mortgage or bank charge on the Scheduled Property, the Vendor covenants to utilize the sale consideration to fully discharge and obtain a No Objection Certificate (NOC) and Mortgage Discharge Deed at their own expense prior to registration.',
    contentTa: 'விற்கப்படும் சொத்தின் மீது ஏதேனும் வங்கி கடன் அல்லது அடமானம் நிலுவையில் இருந்தால், விற்பனையாளர் இந்த விற்பனைத் தொகையைப் பயன்படுத்தி அதை முழுமையாக அடைத்து, பதிவுக்கு முன்னதாக தங்கள் சொந்தச் செலவில் தடையில்லாச் சான்றிதழ் (NOC) மற்றும் அடமான விடுதலைப் பத்திரத்தைப் பெற ஒப்புக்கொள்கிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'tenant_occupancy',
    title: 'Existing Tenant Occupancy Clause',
    category: 'Conditional',
    contentEn: 'The Purchaser acknowledges that the Scheduled Property is currently occupied by tenants, and the Vendor hereby transfers all landlord rights, rental security deposits, and the right to collect future rents to the Purchaser with effect from the date of execution.',
    contentTa: 'அட்டவணை சொத்தில் தற்போது வாடகைதாரர்கள் குடியிருப்பதை வாங்குபவர் ஒப்புக்கொள்கிறார். விற்பனையாளர் தனது நில உரிமையாளர் உரிமைகள், வாடகை வைப்புத் தொகைகள் மற்றும் வருங்கால வாடகையை வசூலிக்கும் உரிமையை இன்று முதல் வாங்குபவருக்கு மாற்றுகிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'gov_acquisition',
    title: 'Government Acquisition Protection',
    category: 'Conditional',
    contentEn: 'The Vendor declares that the Scheduled Property is not subject to any land acquisition notice, road widening project, or municipal reservation by any governmental body or local planning authority, and covenants to indemnify the Purchaser if any such pre-existing acquisition is discovered.',
    contentTa: 'சொத்து எந்தவொரு நில கையகப்படுத்தும் நடவடிக்கை, சாலை விரிவாக்கத் திட்டம் அல்லது அரசாங்க நகராட்சி ஒதுக்கீடுகளுக்கு உட்படவில்லை என்றும், அவ்வாறு ஏதேனும் முந்தைய கையகப்படுத்துதல் கண்டறியப்பட்டால் வாங்குபவருக்கு ஏற்படும் இழப்பை விற்பனையாளர் ஈடுசெய்வார் என்றும் உறுதியளிக்கிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'litigation_disclosure',
    title: 'Litigation Disclosure & Indemnity',
    category: 'Conditional',
    contentEn: 'The Vendor covenants that there are no pending civil, criminal, revenue, or tax litigation proceedings in any court of law or tribunal concerning the Scheduled Property, and that the title of the Vendor is free from any legal challenge or lis pendens.',
    contentTa: 'சொத்து தொடர்பாக எந்தவொரு சிவில், கிரிமினல் அல்லது வருவாய் நீதிமன்றங்களிலும் வழக்குகள் நிலுவையில் இல்லை என்றும், விற்பனையாளரின் சொத்துரிமை எந்தவொரு சட்டரீதியான சவாலுக்கும் உட்படவில்லை என்றும் விற்பனையாளர் உறுதியளிக்கிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'gpa_validation',
    title: 'GPA Validation Clause',
    category: 'Conditional',
    contentEn: 'Where this deed is executed by a General Power of Attorney (GPA) holder, the Principal and the Agent jointly declare that the GPA registered is fully valid, in force, and has not been revoked, cancelled, or terminated as of the date of execution of this deed.',
    contentTa: 'இப்பத்திரம் பொது அதிகாரப் பத்திரம் (GPA) பெற்றவர் மூலம் எழுதப்படும் பட்சத்தில், குறிப்பிட்ட பொது அதிகாரப் பத்திரம் செல்லுபடியாகக்கூடியது என்றும், இன்று வரை அது ரத்து செய்யப்படவில்லை என்றும் அசல் உரிமையாளரும் முகவரும் இணைந்து பிரகடனம் செய்கிறார்கள்.',
    isActive: true,
    isMandatory: false,
  },

  // --- COMPLIANCE COVENANTS ---
  {
    id: 'tn_patta_mutation',
    title: 'Tamil Nadu Revenue Mutation Clause',
    category: 'Compliance',
    contentEn: 'Both parties hereby agree that the Scheduled Property is fully registered under Patta/Chitta/Adangal records of Tamil Nadu Revenue Department, and the Vendor undertakes to provide all administrative assistance and execute necessary mutation applications on the TN e-District portal within thirty (30) days from registration.',
    contentTa: 'சொத்தானது தமிழ்நாட்டின் வருவாய்த்துறை பட்டா, சிட்டா மற்றும் அடங்கல் பதிவேடுகளின் கீழ் முறையாகப் பதிவு செய்யப்பட்டுள்ளது என்றும், விற்பனையாளர் பதிவு செய்யப்பட்ட முப்பது (30) நாட்களுக்குள் தமிழ்நாடு இ-சேவை இணையதளத்தில் பட்டா மாறுதலுக்கான அனைத்து உதவிகளையும் ஒப்புதல்களையும் வழங்க ஒப்புக்கொள்கிறார்.',
    isActive: true,
    isMandatory: false,
  },
  {
    id: 'tn_tslr_compliance',
    title: 'TSLR Town Survey Land Register Compliance',
    category: 'Compliance',
    contentEn: 'The Vendor warrants that the Scheduled Property matches the dimensions, survey limits, and ownership details recorded in the Town Survey Land Register (TSLR) of the municipal corporation, and agrees to indemnify the Purchaser against any administrative discrepancies found in the revenue division.',
    contentTa: 'விற்கப்படும் சொத்தின் பரப்பளவு, எல்லைகள் மற்றும் உரிமை விபரங்கள் அனைத்தும் நகராட்சி மற்றும் மாநகராட்சியின் நகர நில அளவைப் பதிவேட்டுடன் (TSLR) முழுமையாக ஒத்துப்போகிறது என்றும், இதில் ஏதேனும் குளறுபடிகள் கண்டறியப்பட்டால் அதற்கு விற்பனையாளரே பொறுப்பாவார் என்றும் உறுதியளிக்கிறார்.',
    isActive: true,
    isMandatory: false,
  }
];

export const DRAFT_DEEDS = [
  {
    id: 'dft1',
    docNo: 'DEED/2026/0142',
    docType: 'Sale Deed',
    subType: 'Sale in Metro Area',
    partiesCount: 2,
    propertyAddress: 'Velachery Village, Plot No. 12B, Survey No. 142/3A, Sholinganallur Taluk',
    consideration: 7500000,
    status: 'Draft',
    writer: 'V. Sridhar (License No. 1042/2021)',
    date: '2026-06-25',
    progress: 75,
  },
  {
    id: 'dft2',
    docNo: 'DEED/2026/0098',
    docType: 'Gift Settlement Deed',
    subType: 'Gift to Family Member',
    partiesCount: 2,
    propertyAddress: 'Mylapore, Door No. 15, Sree Puram, Survey No. 492/1, Mylapore Taluk',
    consideration: 0,
    status: 'Pending Review',
    writer: 'Selvakumar M. (DEO)',
    date: '2026-06-20',
    progress: 100,
  },
  {
    id: 'dft3',
    docNo: 'DEED/2026/0115',
    docType: 'Sale Deed',
    subType: 'Sale in Panchayat Area',
    partiesCount: 3,
    propertyAddress: 'Chitlapakkam Village, Survey No. 89/1B, Tambaram Taluk',
    consideration: 4200000,
    status: 'Completed',
    writer: 'K. Kathiravan (Lawyer)',
    date: '2026-06-12',
    progress: 100,
  },
  {
    id: 'dft4',
    docNo: 'DEED/2026/0150',
    docType: 'Lease Deed',
    subType: 'Residential Lease',
    partiesCount: 2,
    propertyAddress: 'Thiruvanmiyur, Flat 4A, Ocean View, Survey No. 340/5, Mylapore Taluk',
    consideration: 45000,
    status: 'Draft',
    writer: 'V. Sridhar (License No. 1042/2021)',
    date: '2026-06-28',
    progress: 30,
  }
];

export const DUMMY_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'al1',
    timestamp: '2026-06-29T00:15:00Z',
    user: 'raj.asusrog@gmail.com',
    role: 'Super Admin',
    action: 'Document Validation Run',
    details: 'Triggered AI validation checks on Sale Deed DEED/2026/0142. No critical warnings.',
    ipAddress: '192.168.1.10'
  },
  {
    id: 'al2',
    timestamp: '2026-06-28T16:30:22Z',
    user: 'V. Sridhar',
    role: 'Document Writer',
    action: 'Draft Created',
    details: 'Initiated Sale Deed drafting for Purchaser Selvakumar M. with survey details.',
    ipAddress: '103.42.112.5'
  },
  {
    id: 'al3',
    timestamp: '2026-06-28T10:12:05Z',
    user: 'R. Rajeshwari',
    role: 'Client',
    action: 'Profile Updated',
    details: 'Updated bank details and PAN card details on registration profile.',
    ipAddress: '201.23.4.156'
  },
  {
    id: 'al4',
    timestamp: '2026-06-27T11:45:00Z',
    user: 'M. Anand',
    role: 'Auditor',
    action: 'Document Approval',
    details: 'Approved Gift Deed DEED/2026/0098 for registration sub-registrar submission.',
    ipAddress: '122.164.2.89'
  }
];

export const DUMMY_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'n1',
    title: 'Guideline Value Mismatch Alert',
    message: 'Sale Deed DEED/2026/0142 indicates consideration value below registry guideline value of Velachery Village!',
    type: 'warning',
    timestamp: '2026-06-29T00:22:00Z',
    read: false,
  },
  {
    id: 'n2',
    title: 'AI Verification Completed',
    message: 'Automatic boundary cross-verification completed successfully for Survey No. 492/1.',
    type: 'success',
    timestamp: '2026-06-28T18:10:00Z',
    read: false,
  },
  {
    id: 'n3',
    title: 'New Client Profile Created',
    message: 'Client profile M. Selvakumar added by Writer V. Sridhar.',
    type: 'info',
    timestamp: '2026-06-28T11:05:00Z',
    read: true,
  },
  {
    id: 'n4',
    title: 'Double Registration Threat Blocked',
    message: 'Registry Intelligence flagged Survey 89/1B in Chitlapakkam Village as having a pending injunction order!',
    type: 'error',
    timestamp: '2026-06-27T09:12:00Z',
    read: false,
  }
];
